version: '3'
services:
  nginx:
    container_name: nginx-container
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/www/html:/var/www/html
    depends_on:
      - app

  app:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    expose:
      - "8080"
    command: mvn clean spring-boot:run